[package]
name = "aoc24"
version = "0.2.0"
edition = "2021"
authors = ["Louis Borres"]

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4", features = ["derive"] }
csv = "1.3"
dotenvy = "0.15.7"
tracing = "0.1"
tracing-subscriber = "0.3"
